INSERT INTO Vaccines (name, disease, eligible_age, eligible_age_words) 
VALUES 
    ('BCG', 'Tuberculosis', 0, 'At Birth'),
    ('0PV-0', 'Polio', 0, 'At Birth'),
    ('HEP-BD', 'Viral Hepatitis B', 0, 'At Birth'),
    ('PENTA-1', 'Diptheria, Tetanus, Whooping Cough, Hepatitis B, Haemophilus influenzae b infections', 1.5, 'At 1 and a half months'),
    ('PNEUMO 1', 'Infection due to pneumococcus', 1.5, 'At 1 and a half months'),
    ('0PV-1', 'Polio', 1.5, 'At 1 and a half months'),
    ('ROTA 1', 'Rotavirus diarrhea', 1.5, 'At 1 and a half months'),
    ('PENTA-2', 'Diptheria, Tetanus, Whooping Cough, Hepatitis B, Hib infections', 2.5, 'At 2 and a half months'),
    ('PNEUMO 2', 'Infection due to pneumococcus', 2.5, 'At 2 and a half months'),
    ('0PV-2', 'Polio', 2.5, 'At 2 and a half months'),
    ('ROTA 2', 'Rotavirus diarrhea', 2.5, 'At 2 and a half months'),
    ('TPIn-1', 'Malaria', 2.5, 'At 2 and a half months'),
    ('PENTA-3', 'Diptheria, Tetanus, Whooping Cough, Hepatitis B, Hib infections', 3.5, 'At 3 and a half months'),
    ('PNEUMO 3', 'Infection due to pneumococcus', 3.5, 'At 3 and a half months'),
    ('0PV-3', 'Polio', 3.5, 'At 3 and a half months'),
    ('ROTA 3', 'Rotavirus diarrhea', 3.5, 'At 3 and a half months'),
    ('IPV-1', 'Polio', 3.5, 'At 3 and a half months'),
    ('TPIn-2', 'Malaria', 3.5, 'At 3 and a half months'),
    ('Vit A', 'Avitaminosis A', 6, 'At 6 months'),
    ('RTS,S', 'Malaria', 6, 'At 6 months'),
    ('TPIn-3', 'Malaria', 6, 'At 6 months'),
    ('RTS,S', 'Malaria', 7, 'At 7 months'),
    ('MR1', 'Measles-Rubella', 9, 'At 9 months'),
    ('VVA', 'Yellow Fever', 9, 'At 9 months'),
    ('IPV-2', 'Polio', 9, 'At 9 months'),
    ('RTS,S', 'Malaria', 9, 'At 9 months'),
    ('TPIn-4', 'Malaria', 9, 'At 9 months'),
    ('Vit A', 'Avitaminosis A', 12, 'At 12 months'),
    ('MEBENDAZOLE', 'Intestinal Parasitosis', 12, 'At 12 months'),
    ('MR2', 'Measles-Rubella', 15, 'At 15 months'),
    ('MEN ACYW135', 'Meningococcal meningitis type A, ACYW123', 15, 'At 15 months'),
    ('TPIn-5', 'Malaria', 15, 'At 15 months'),
    ('Vit A', 'Avitaminosis A', 18, 'At 18 months'),
    ('MEBENDAZOLE', 'Intestinal Parasitosis', 18, 'At 18 months'),
    ('RTS,S', 'Malaria', 24, 'At 24 months'),
    ('Vit A', 'Avitaminosis A', 24, 'At 24 months'),
    ('MEBENDAZOLE', 'Intestinal Parasitosis', 24, 'At 24 months'),
    ('Vit A', 'Avitaminosis A', 30, 'At 30 months'),
    ('MEBENDAZOLE', 'Intestinal Parasitosis', 30, 'At 30 months'),
    ('HEP-BD', 'Viral Hepatitis B', 30, 'At 30 months'),
    ('Vit A', 'Avitaminosis A', 36, 'At 36 months'),
    ('MEBENDAZOLE', 'Intestinal Parasitosis', 36, 'At 36 months'),
    ('Vit A', 'Avitaminosis A', 42, 'At 42 months'),
    ('MEBENDAZOLE', 'Intestinal Parasitosis', 42, 'At 42 months'),
    ('Vit A', 'Avitaminosis A', 48, 'At 48 months'),
    ('MEBENDAZOLE', 'Intestinal Parasitosis', 48, 'At 48 months'),
    ('Vit A', 'Avitaminosis A', 54, 'At 54 months'),
    ('MEBENDAZOLE', 'Intestinal Parasitosis', 54, 'At 54 months'),
    ('HPV', 'Human Papilloma Virus Infection', 216, 'At 216 months');
